### ISSUE TITLE
Cannot launch apache/apacheLB recipes

### ISSUE THREAD

**Issue by justicel** [CloudifySource/cloudify-recipes#65]
I am running the 2.5.0-ga release of cloudify. I know there are some outstanding bugs, and perhaps this is one of them... but when running several recipes, including apache and apacheLB I get the following kinds of errors:

Caused by: java.io.IOException: Cannot run program "/root/gigaspaces/work/processing-units/default_apache_1_2115708570/ext/./install.sh": java.io.IOException: error=2, No such file or directory
    at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:862)
    at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:481)
    at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:495)
    at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
    ... 10 more
Caused by: java.io.IOException: java.io.IOException: error=2, No such file or directory
    ... 15 more

As far as I can tell, Cloudify is referencing the wrong location for the extracted work-unit. I looked on the server at the same time it was attempting to run this script and it was showing a different ID# than was actually referenced. Some of the old recipes work fine, like tomcat. Any ideas on this?

**Comment by justicel** [comment]
Ack! I figured it out. Stupid CRLF issues in git for windows. Sorry about that!
