### ISSUE TITLE
redis: No such file or directory

### ISSUE THREAD

**Issue by josh-at-knoesis** [CloudifySource/cloudify-recipes#66]
I see that this recipe is still under construction, but I'm in need of it for this: https://cloudifysource.zendesk.com/entries/23704872-Requesting-help-with-first-application-recipe-development-

The following error was produced on a bootstrap-local deployment.

Please advise.

Thanks,
Joshua

[cloudify-1/192.168.1.106] redis_caching-1 INIT invoked
[cloudify-1/192.168.1.106] redis_caching-1 INIT failed. Reason: Event lifecycle external process exited with abnormal status code: 1     [mkdir] Created dir: /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install
      [get] Getting: http://redis.googlecode.com/files/redis-2.4.5.tar.gz
      [get] To: /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install/redis-2.4.5.tar.gz
    [untar] Expanding: /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install/redis-2.4.5.tar.gz into /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install
Caught: : Execute failed: java.io.IOException: Cannot run program "make" (in directory "/home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install/redis-2.4.5"): java.io.IOException: error=2, No such file or directory
: Execute failed: java.io.IOException: Cannot run program "make" (in directory "/home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install/redis-2.4.5"): java.io.IOException: error=2, No such file or directory
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:675)
    at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at redis_install.run(redis_install.groovy:18)
Caused by: java.io.IOException: Cannot run program "make" (in directory "/home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_693200230/ext/install/redis-2.4.5"): java.io.IOException: error=2, No such file or directory
    at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:862)
    at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:481)
    at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:495)
    at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
    ... 8 more
Caused by: java.io.IOException: java.io.IOException: error=2, No such file or directory
    ... 13 more
 [ERROR]
[cloudify-1/192.168.1.106] redis_caching-1 STOP invoked
[cloudify-1/192.168.1.106] redis_caching-1 STOP completed, duration: 0.0 seconds [OK]
....
[cloudify-1/192.168.1.106] mysql-1 INSTALL completed, duration: 41.0 seconds [OK]
[cloudify-1/192.168.1.106] mysql-1 START invoked
.....
[mysql] Deployed 1 planned 1
Service "mysql" successfully installed (1 Instances)
.....
[cloudify-1/192.168.1.106] redis_caching-1 INIT invoked
[cloudify-1/192.168.1.106] redis_caching-1 INIT failed. Reason: Event lifecycle external process exited with abnormal status code: 1     [mkdir] Created dir: /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install
      [get] Getting: http://redis.googlecode.com/files/redis-2.4.5.tar.gz
      [get] To: /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install/redis-2.4.5.tar.gz
    [untar] Expanding: /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install/redis-2.4.5.tar.gz into /home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install
Caught: : Execute failed: java.io.IOException: Cannot run program "make" (in directory "/home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install/redis-2.4.5"): java.io.IOException: error=2, No such file or directory
: Execute failed: java.io.IOException: Cannot run program "make" (in directory "/home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install/redis-2.4.5"): java.io.IOException: error=2, No such file or directory
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:675)
    at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at redis_install.run(redis_install.groovy:18)
Caused by: java.io.IOException: Cannot run program "make" (in directory "/home/ubuntu/gigaspaces-cloudify-2.5.0-ga/work/processing-units/hotel_redis_caching_1_1672302404/ext/install/redis-2.4.5"): java.io.IOException: error=2, No such file or directory
    at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:862)
    at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:481)
    at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:495)
    at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
    ... 8 more
Caused by: java.io.IOException: java.io.IOException: error=2, No such file or directory
    ... 13 more
 [ERROR]
[cloudify-1/192.168.1.106] redis_caching-1 STOP invoked
[cloudify-1/192.168.1.106] redis_caching-1 STOP completed, duration: 0.0 seconds [OK]
....

**Comment by josh-at-knoesis** [comment]
I just looked closer at this redis problem.  The error stems from the make command not being available at the time of invocation.  I'm on Ubuntu 12.04.  Please consider updating this recipe to install for this dependency.

Thanks,
Joshua

**Comment by tamirko** [comment]
We will fix it ,but I don't have an ETA on that.
You can fix it and send a pull request and we''ll be happy to accept it :)
